# Generated by Django 6.0.3 on 2026-05-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_adintegration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_tg_chat',
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_handle',
            field=models.CharField(blank=True, help_text='Ник пользователя без символа @', max_length=100, null=True, verbose_name='Ник в Telegram'),
        ),
    ]
