# Generated by Django 6.0.3 on 2026-05-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_eridintegration_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telegram_handle',
        ),
        migrations.AddField(
            model_name='eridintegration',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на опубликованное видео'),
        ),
        migrations.AddField(
            model_name='savedcontractor',
            name='channel_url',
            field=models.URLField(blank=True, help_text='Основная площадка блогера', max_length=500, null=True, verbose_name='Ссылка на основной канал'),
        ),
        migrations.AddField(
            model_name='user',
            name='ok',
            field=models.URLField(blank=True, null=True, verbose_name='Одноклассники (ссылка)'),
        ),
        migrations.AddField(
            model_name='user',
            name='other',
            field=models.TextField(blank=True, null=True, verbose_name='Другое (дополнительно)'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram (username/link)'),
        ),
        migrations.AddField(
            model_name='user',
            name='vk',
            field=models.URLField(blank=True, null=True, verbose_name='ВКонтакте (ссылка)'),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='WhatsApp (номер/link)'),
        ),
    ]
