# Generated by Django 6.0.3 on 2026-04-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_productad_external_url_productad_budget_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productad',
            old_name='link_site',
            new_name='link_other',
        ),
        migrations.RenameField(
            model_name='productad',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='productad',
            name='image_url',
        ),
        migrations.AddField(
            model_name='productad',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на фото'),
        ),
    ]
