# Generated by Django 6.0.3 on 2026-05-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_message_ad_remove_message_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloggerprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productad',
            name='budget',
        ),
        migrations.AddField(
            model_name='advertiserprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Расчетный счет'),
        ),
        migrations.AddField(
            model_name='advertiserprofile',
            name='bik',
            field=models.CharField(blank=True, max_length=9, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='advertiserprofile',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Доп. поля'),
        ),
        migrations.AddField(
            model_name='advertiserprofile',
            name='inn',
            field=models.CharField(blank=True, max_length=12, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='advertiserprofile',
            name='legal_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Юр. адрес'),
        ),
        migrations.AddField(
            model_name='advertiserprofile',
            name='ogrn',
            field=models.CharField(blank=True, max_length=15, verbose_name='ОГРН'),
        ),
        migrations.AddField(
            model_name='advertiserprofile',
            name='website',
            field=models.URLField(blank=True, verbose_name='Сайт'),
        ),
        migrations.AddField(
            model_name='bloggerprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Расчетный счет'),
        ),
        migrations.AddField(
            model_name='bloggerprofile',
            name='bank_receiver',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО получателя'),
        ),
        migrations.AddField(
            model_name='bloggerprofile',
            name='bik',
            field=models.CharField(blank=True, max_length=9, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='bloggerprofile',
            name='channel_description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='bloggerprofile',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Доп. поля'),
        ),
        migrations.AddField(
            model_name='bloggerprofile',
            name='inn',
            field=models.CharField(blank=True, max_length=12, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='productad',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name='Доп. информация'),
        ),
        migrations.AddField(
            model_name='productad',
            name='is_barter',
            field=models.BooleanField(default=True, verbose_name='Только бартер'),
        ),
        migrations.AddField(
            model_name='productad',
            name='short_description',
            field=models.TextField(blank=True, max_length=30, verbose_name='Краткое описание'),
        ),
    ]
