# Generated by Django 6.0.3 on 2026-05-13 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_bloggerprofile_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(verbose_name='Ссылка на ролик')),
                ('timestamp', models.IntegerField(default=0)),
                ('product_name', models.CharField(blank=True, max_length=255, verbose_name='Товар')),
                ('brand', models.CharField(blank=True, max_length=255, verbose_name='Бренд')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость')),
                ('channel_name', models.CharField(blank=True, max_length=255)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
