# Generated by Django 6.0.3 on 2026-05-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_user_current_tg_chat_user_telegram_handle'),
    ]

    operations = [
        migrations.CreateModel(
            name='EridIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogger_name', models.CharField(max_length=255)),
                ('advertiser_name', models.CharField(max_length=255)),
                ('channel_url', models.URLField()),
                ('creative_name', models.CharField(max_length=255)),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('erid', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedContractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, unique=True, verbose_name='Внешний ID в ОРД')),
                ('name', models.CharField(max_length=255, verbose_name='Название / ФИО')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН')),
                ('role', models.CharField(choices=[('advertiser', 'Рекламодатель'), ('blogger', 'Блогер')], max_length=50)),
            ],
        ),
    ]
