# Generated by Django 6.0.3 on 2026-05-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_eridintegration_savedcontractor'),
    ]

    operations = [
        migrations.CreateModel(
            name='KktuCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код ККТУ')),
                ('name', models.CharField(max_length=500, verbose_name='Название категории')),
                ('parent_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код родителя')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Код ККТУ ОРД',
                'verbose_name_plural': 'Коды ККТУ ОРД',
                'ordering': ['code'],
            },
        ),
    ]
