# Generated by Django 6.0.3 on 2026-05-19 07:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_kktucode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eridintegration',
            options={'ordering': ['-created_at'], 'verbose_name': 'Интеграция ОРД (ERID)', 'verbose_name_plural': 'Интеграции ОРД (ERID)'},
        ),
        migrations.AlterModelOptions(
            name='savedcontractor',
            options={'verbose_name': 'Контрагент ОРД', 'verbose_name_plural': 'Контрагенты ОРД'},
        ),
        migrations.AddField(
            model_name='eridintegration',
            name='invoice_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма по акту'),
        ),
        migrations.AddField(
            model_name='eridintegration',
            name='kktu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.kktucode', verbose_name='Код ККТУ'),
        ),
        migrations.AddField(
            model_name='savedcontractor',
            name='citizenship',
            field=models.CharField(choices=[('rf', 'РФ'), ('foreign', 'Иностранец')], default='rf', max_length=10, verbose_name='Гражданство'),
        ),
        migrations.AddField(
            model_name='savedcontractor',
            name='contractor_type',
            field=models.CharField(choices=[('ur', 'Юрлицо'), ('fiz', 'Физлицо'), ('ip', 'ИП')], default='ur', max_length=10, verbose_name='Тип контрагента'),
        ),
        migrations.AddField(
            model_name='savedcontractor',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна (для иностранцев)'),
        ),
        migrations.AddField(
            model_name='savedcontractor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedcontractor',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон (для физлиц)'),
        ),
        migrations.AlterField(
            model_name='eridintegration',
            name='advertiser_name',
            field=models.CharField(max_length=255, verbose_name='Рекламодатель'),
        ),
        migrations.AlterField(
            model_name='eridintegration',
            name='blogger_name',
            field=models.CharField(max_length=255, verbose_name='Блогер'),
        ),
        migrations.AlterField(
            model_name='eridintegration',
            name='channel_url',
            field=models.URLField(verbose_name='Ссылка на площадку'),
        ),
        migrations.AlterField(
            model_name='eridintegration',
            name='creative_name',
            field=models.CharField(max_length=255, verbose_name='Название ролика/креатива'),
        ),
        migrations.AlterField(
            model_name='eridintegration',
            name='erid',
            field=models.CharField(max_length=100, unique=True, verbose_name='Токен (ERID)'),
        ),
        migrations.AlterField(
            model_name='eridintegration',
            name='invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата акта/счета'),
        ),
        migrations.AlterField(
            model_name='eridintegration',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер акта/счета'),
        ),
        migrations.AlterField(
            model_name='savedcontractor',
            name='role',
            field=models.CharField(choices=[('advertiser', 'Рекламодатель'), ('blogger', 'Блогер')], max_length=50, verbose_name='Роль в интеграции'),
        ),
        migrations.CreateModel(
            name='OrdContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, unique=True, verbose_name='Внешний ID договора в ОРД')),
                ('number', models.CharField(max_length=100, verbose_name='Номер договора')),
                ('date_sign', models.DateField(verbose_name='Дата заключения договора')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_adv', to='core.savedcontractor', verbose_name='Рекламодатель')),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_blog', to='core.savedcontractor', verbose_name='Блогер')),
            ],
            options={
                'verbose_name': 'Договор ОРД',
                'verbose_name_plural': 'Договоры ОРД',
                'unique_together': {('advertiser', 'blogger')},
            },
        ),
        migrations.AddField(
            model_name='eridintegration',
            name='ord_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='core.ordcontract', verbose_name='Договор ОРД'),
        ),
    ]
